name: CI - Test de Base  # Nom du workflow

on:
  push:
    branches: [main]  # Déclenche sur un push vers la branche 'main'
  pull_request:
    branches: [main]  # Déclenche sur une pull request vers la branche 'main'

jobs:
  hello:
    runs-on: ubuntu-latest  # Environnement du runner

    steps:
      - name: Afficher un message
        run: echo "CI fonctionne !"  # Affiche le message dans le terminal
